development:
  adapter: postgresql
  encoding: unicode
  database: myapp_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_prod
  pool: 5
  timeout: 5000
